### ISSUE TITLE
composer install fails

### ISSUE THREAD

**Issue by DirkHeinke** [swp-unikat/Einschreibesystem#333]
When executing `php composer.phar install` the installation fails:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DOMDocument" from the global namespace.
Did you forget a "use" statement? in /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(284): Symfony\Component\Config\Util\XmlUtils::loadFile('/.../ww...', Array)
#1 /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/.../ww...')
#2 /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(58): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony in /.../www/Einschreibesystem/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52

```

**Comment by DirkHeinke** [comment]
`php-xml` was not installed
